- name: ensure the jenkins apt repository key is installed
  ansible.builtin.get_url:
    url: "{{jenkins_repo}}/jenkins.io-2023.key"
    dest: "/usr/share/keyrings/jenkins-keyring.asc"
    mode: '0644' # Recommended permission for keyrings

- name: ensure the repository is configured
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] {{jenkins_repo}} binary/"
    state: present
    filename: jenkins # Optional: specify a filename for the repo

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java & fontconfig
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{java}}"
    - fontconfig
    - nfs-common
    - mount # Generally safe to keep, though often already present

- name: ensure jenkins is installed
  ansible.builtin.apt:
    name: jenkins
    state: latest

- name: Stop Jenkins service before EFS mount
  ansible.builtin.service:
    name: jenkins
    state: stopped
  ignore_errors: yes # In case Jenkins isn't running for the first time

- name: Ensure /var/lib/jenkins directory exists
  ansible.builtin.file:
    path: /var/lib/jenkins
    state: directory
    # No recurse here unless you specifically want to clear existing data.
    # We will set ownership after the mount.

- name: Ensure EFS is mounted at /var/lib/jenkins and entry exists in /etc/fstab
  ansible.posix.mount:
    path: /var/lib/jenkins
    src: "{{efs}}.efs.ap-south-1.amazonaws.com:/"
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev,noatime,nodiratime" # Recommended EFS mount options
    state: mounted # This will mount it and add to fstab

- name: Change permission of mounted EFS back to Jenkins user
  ansible.builtin.file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    state: directory
    recurse: yes # Apply ownership to all contents on the EFS

- name: Mount all file systems from fstab (if not already mounted)
  ansible.builtin.command: mount -a
  when: ansible_mounts | selectattr('mount', '==', '/var/lib/jenkins') | list | length == 0
  # This task is less critical if 'state: mounted' in the previous task worked,
  # but acts as a safeguard.

- name: Start Jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started

- name: Check if port 8080 is listening
  ansible.builtin.wait_for:
    port: 8080
    timeout: 180
    msg: "Timeout waiting for 8080 to respond"
  register: port_check
  ignore_errors: yes

- name: Print message if Jenkins is not running
  ansible.builtin.debug:
    msg: "*== Jenkins NOT Running ==*"
  when: port_check.failed == true
